name: Build and deploy lab website to github pages

on:
  push:
    branches:
      - master
      - dev

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: False
      - name: Install R
        uses: r-lib/actions/setup-r@v2
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install Dependencies
        run: |
          npm install
          npm run install:R
          gem install bundler
          bundle install
      - name: Build
        run: |
          npm run build
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref_name == 'master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: devbrainlab.org
